"""added card_verified field to user

Revision ID: f20bfb252d2b
Revises: 8ab2e07b2df8
Create Date: 2024-11-27 11:01:36.046669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f20bfb252d2b'
down_revision: Union[str, None] = '8ab2e07b2df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_otp_verifications_id', table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.add_column('users', sa.Column('is_card_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_card_verified')
    op.create_table('otp_verifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('otp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='otp_verifications_pkey'),
    sa.UniqueConstraint('email', name='otp_verifications_email_key')
    )
    op.create_index('ix_otp_verifications_id', 'otp_verifications', ['id'], unique=False)
    # ### end Alembic commands ###
